apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: coremvcdocker
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: coremvcdocker
    spec:
      containers:
        - image: "ashwilliams/coremvcdocker"
          imagePullPolicy: Always
          name: coremvcdocker
          ports:
            - containerPort: 80